-- Update ALL seed profiles with longer bios and better prompts

DO $$
DECLARE
    long_bios TEXT[] := ARRAY[
        'Coffee addict with a serious addiction to trying every new cafe that opens in the city. I spend my weekends exploring hidden gems, from tiny espresso bars in the Village to trendy roasteries in Williamsburg. Looking for someone to explore the city with, whether that means getting lost in a new neighborhood, finding the best slice of pizza at 2am, or just sitting in the park watching the world go by. I believe the best relationships start with a really good conversation over really good coffee.',
        'Musician by night, designer by day. I work at a startup downtown but my real passion is playing guitar in a jazz band every Thursday at a little bar in the East Village. Love trying new restaurants - my friends joke that I should have been a food critic instead. I''ve eaten at basically every ramen spot in Manhattan and I have very strong opinions about which ones are worth the wait. When I''m not working or playing music, you''ll find me at a gallery opening or hunting for vintage records.',
        'Photographer and traveler who''s been to 30 countries and counting. Always planning the next adventure, whether it''s a weekend road trip upstate or a month-long backpacking trip through Southeast Asia. I document everything - my apartment is basically a gallery of prints from my travels. I''m looking for someone who gets excited about booking a spontaneous flight, who doesn''t mind eating street food for dinner, and who appreciates a really good sunset. Let''s make some memories worth photographing.',
        'Tech nerd with a passion for cooking that I take way too seriously. I''ve taught myself to make everything from fresh pasta to proper French pastries. My dinner parties are legendary among my friends - I once spent three days preparing a seven-course tasting menu for twelve people. I work in AI but I''m not one of those tech bros, I promise. I read actual books, I go outside, and I can hold a conversation about things other than work. Make me laugh and I''ll cook you the best meal of your life.',
        'Yoga instructor and bookworm seeking deep conversations and someone who understands the importance of balance. I teach vinyasa at a studio in Chelsea but I also run a book club that meets every month at a wine bar in the West Village. Currently reading way too many books at once, as always. I believe in starting the day with meditation and ending it with a good glass of wine. Looking for someone who values personal growth, isn''t afraid of vulnerability, and knows that the best things in life take time to cultivate.',
        'Artist based in NYC, working out of a studio in Bushwick that I share with three other painters. My work is abstract expressionist - lots of color, lots of emotion, lots of coffee stains on my clothes. Will definitely show you my studio on the second date if the first one goes well. I''m looking for someone who appreciates creativity, doesn''t mind paint under my fingernails, and understands that sometimes I need to disappear into my work for a few days. But when I''m present, I''m really present.',
        'Finance by day, DJ by night - yes, I contain multitudes. I spend my weekdays analyzing spreadsheets and my weekends spinning records at warehouse parties in Brooklyn. Rooftop season is my favorite season because it combines my two loves: good music and good views. I''ve been collecting vinyl since college and my apartment looks like a record store exploded in it. Looking for someone who can hang at a sweaty dance party until 4am but also enjoys a quiet Sunday morning with the paper.',
        'Startup founder trying to change the world, one line of code at a time. Work hard, play harder - that''s not just a cliche for me, it''s a lifestyle. I founded my company three years ago and we just closed our Series B, so things are finally starting to calm down a little. I''m looking for someone who understands ambition but also knows how to unplug. My ideal weekend involves working out, brunch with friends, and then absolutely nothing productive for the rest of the day.',
        'Teacher who believes that education is the most important thing we can invest in. I teach high school English in the Bronx and it''s the most challenging and rewarding thing I''ve ever done. On weekends, I decompress by hiking in the Hudson Valley or trying new coffee shops around the city. I have very strong opinions about books - Jane Austen is overrated, fight me - and I''m always looking for good recommendations. If you can make me see a classic in a new way, I''m already intrigued.',
        'Writer working on my first novel while pretending to work on freelance assignments. You''ll probably find me at a cafe, laptop open, pretending I''m being productive while actually people-watching and eavesdropping on conversations for material. I''ve been working on this book for two years and I''m finally in the home stretch. I need someone who understands creative types, who doesn''t mind when I zone out mid-conversation because I just thought of the perfect sentence, and who will celebrate with me when this thing finally gets published.',
        'Nurse with a love for travel and adventure. I work night shifts at a hospital in the city, which means my schedule is weird but also means I have weekdays free for exploring. I''ve been to six continents and my goal is to hit all seven before I turn 35. When I''m not working or traveling, I''m training for my next marathon or trying a new hiking trail. Looking for someone who can keep up with my energy and doesn''t mind planning trips six months in advance.',
        'Chef who can cook you a dinner you''ll never forget. I trained at the Culinary Institute and worked my way up from line cook to sous chef at a Michelin-starred restaurant in Manhattan. Now I''m planning to open my own place in the next couple years. I take food very seriously but I don''t take myself too seriously. Wine is definitely included in any dinner I make - I have strong opinions about natural wines and I''m not afraid to share them. Let me cook for you and see where things go.',
        'Lawyer who''s actually fun at parties - I know, we''re rare. I work in entertainment law, which means my job is basically helping creative people protect their work. It''s way more interesting than it sounds. Outside of work, I''m the friend who always knows about the new restaurant or bar before anyone else. I read the New Yorker cover to cover, I have strong opinions about the best martini in the city, and I can talk about almost anything for hours. Looking for someone equally curious.',
        'Physical therapist helping people recover from injuries and get back to doing what they love. There''s nothing more rewarding than watching someone who couldn''t walk six months ago run their first 5K. I''ll fix your posture - seriously, you''re probably slouching right now - and maybe steal your heart in the process. I practice what I preach: I work out six days a week, I eat clean most of the time, and I get eight hours of sleep. But I also believe in balance, so yes, I''ll eat pizza with you.',
        'Marketing exec who knows all the best brunch spots in every neighborhood. It''s basically my job to know what''s cool before it''s cool, and I take that responsibility very seriously. I''ve worked at agencies, startups, and big tech companies, and I''ve learned something from each one. Currently leading brand at a company you''ve definitely heard of. Looking for someone who appreciates good design, understands the value of a strong personal brand, and doesn''t mind me taking photos of our food for Instagram.',
        'Architect designing buildings by day and designing my perfect match in my head by night. Could be you - I''ll know it when I see it. I''ve worked on projects all over the city, from residential high-rises to museum renovations. I think about space and light and how they make people feel. I''m looking for someone who notices the details, who can appreciate a perfectly proportioned room, and who understands that design is everywhere, from the chair you''re sitting in to the app you''re swiping on right now.',
        'Doctor who somehow still has a social life despite the insane hours. I work in emergency medicine, which means every day is different and I''ve seen things that would make great stories at dinner parties. When I''m not at the hospital, I''m usually exploring the city, trying new restaurants, or catching up on sleep. I''m looking for someone patient who understands that my schedule can be unpredictable but also knows that when I''m off, I''m fully present and ready for adventure.',
        'Investment banker trying to have work-life balance - yes, I know that sounds like an oxymoron. I work hard during the week but I protect my weekends fiercely. I''ve learned that life is too short to just grind and never enjoy the fruits of your labor. I love good food, good wine, and good company. I''m looking for someone who has their own thing going on, who doesn''t need me to complete them but wants to build something together anyway.',
        'Actor and model working my way up in the industry while bartending to pay the bills. You might have seen me in a commercial or two, or maybe that one episode of Law & Order where I played "Concerned Bystander #2." I take my craft seriously but I don''t take myself too seriously. When I''m not auditioning or working, I''m probably at a museum or trying to find the best sushi in the city. I have very specific sushi opinions and I''m not afraid to share them.',
        'Grad student surviving on coffee, optimism, and the occasional good date. I''m getting my PhD in neuroscience, which means I spend a lot of time thinking about how brains work - including the ones responsible for swiping on dating apps. I''m looking for someone who can hold an interesting conversation, who doesn''t mind my weird schedule, and who understands that I''m broke but interesting. Once I get my degree and a real job, I promise I''ll upgrade our date spots.',
        'Personal trainer who will definitely try to get you to work out with me eventually, but I promise it''ll be fun. I believe fitness should be enjoyable, not punishing. I got into this field because I saw how transformative it can be for people''s confidence and mental health. Outside the gym, I''m a total foodie - yes, trainers can eat pizza and burgers too. Looking for someone who takes care of themselves but knows how to have a good time.',
        'Engineer building things at a startup you''ve probably used today. I love the challenge of solving hard problems and shipping products that millions of people use. But I''m not a stereotypical engineer - I''m actually pretty social, I go outside regularly, and I can talk about things other than code. On weekends you''ll find me rock climbing, trying new restaurants, or building random projects in my apartment. I''m looking for someone curious and ambitious.',
        'Journalist who will definitely ask you a lot of questions on our first date - it''s an occupational hazard. I cover tech and startups, which means I''m constantly learning about new things and meeting interesting people. I got into journalism because I''m endlessly curious about how the world works. I''m looking for someone who has stories to tell, opinions to share, and doesn''t mind being interviewed over drinks. I promise the article won''t be about you.',
        'Social worker with a dark sense of humor - it''s how I cope with the heavy stuff I deal with at work. I spend my days helping families in crisis, which is incredibly rewarding but also emotionally exhausting. I need someone who can help me decompress, who doesn''t take everything too seriously, and who understands that sometimes I just need to watch trashy TV and not think about anything important.',
        'Bartender who can make you the perfect cocktail for any mood. I''ve been doing this for eight years and I''ve learned to read people pretty well. I love the theater of a good bar - the drinks, the atmosphere, the conversations with strangers at 2am. I work nights and weekends, so my schedule is weird, but I promise I''m worth the calendar gymnastics. Looking for someone who appreciates a well-crafted drink and isn''t afraid of a late-night date.',
        'UX designer who thinks your dating profile could use some work - but I''ll help you fix it. I spend my days making apps easier to use, and I can''t help but apply that thinking to everything, including relationships. I believe good design is about understanding people and their needs. I''m looking for someone who pays attention to details, who can give and receive feedback well, and who understands that great things take iteration.',
        'Musician seeking someone to harmonize with - literally and figuratively. I play multiple instruments and I''m in two different bands right now, which keeps me pretty busy. Music is my first love, but I have room in my heart for more. I''m looking for someone who appreciates live music, doesn''t mind late-night gigs, and might even let me write a song about them if things go well.',
        'Photographer looking for my next muse - and maybe something more. I shoot mostly portraits and street photography, and I''m always looking for interesting faces and stories. My apartment is full of prints and photo books, and my camera is basically an extension of my arm. Looking for someone who''s comfortable in front of the camera, or at least willing to be photographed occasionally for my Instagram.',
        'Dancer with moves both on and off the dance floor. I''ve been dancing since I was five and it''s still my favorite way to express myself. I teach contemporary dance at a studio in Brooklyn and perform whenever I can. I''m looking for someone who appreciates movement, isn''t afraid to dance in public, and understands that a good dance partner in life is even more important than one in the studio.',
        'Veterinarian who will definitely ask to see pictures of your pet within the first five minutes of meeting you. Animals are my life - I have a rescue dog named Mango who is objectively the best dog in NYC. I got into this field because I believe in treating all creatures with compassion and care. Looking for someone who loves animals, preferably has a pet, and doesn''t mind that I might come home smelling like dog occasionally.',
        'Scientist by day, aspiring comedian by night. I work in a biotech lab developing new treatments, which is fascinating but not exactly dinner conversation material. So I started doing open mics as a way to connect with normal humans about normal things. I''m looking for someone who can appreciate both a peer-reviewed journal and a well-timed punchline.',
        'Professor who promises not to lecture you - at least not on the first date. I teach literature at a small college in the city and I genuinely love what I do. There''s nothing better than watching a student connect with a text for the first time. Outside the classroom, I''m a regular person who likes good food, live music, and terrible reality TV. Looking for someone who reads but doesn''t judge my trashy guilty pleasures.',
        'Real estate agent who found my dream apartment and is now looking for someone to share it with. I spend my days showing people around the city, so I know all the best neighborhoods and hidden gems. I love NYC and I love helping people find their place in it. Looking for someone who appreciates a good apartment, understands the value of outdoor space, and doesn''t mind that I''m always checking Zillow.',
        'Therapist who won''t analyze you - much. I specialize in couples counseling, which gives me a pretty unique perspective on relationships. I know what works and what doesn''t, and I''m looking for something real. I believe in communication, vulnerability, and doing the work. But I also know how to turn off therapist mode and just be a person who wants to get to know you.',
        'Publicist with all the good party invites - and I''m looking for someone to bring as my plus one. I work with celebrities and brands, which means my job is basically professional socializing. I love the energy of events and I''m great at working a room. Looking for someone who can hold their own in a crowd, makes a great first impression, and doesn''t mind being my date to random industry events.',
        'Film editor and I''ll cut right to the chase - I''m looking for something real. I spend my days in a dark room cutting together stories, which is incredibly satisfying but also pretty solitary. I need someone who can drag me outside occasionally, who appreciates a good movie as much as I do, and who understands that sometimes the best version of a story requires patience and revision.',
        'Data scientist looking for chemistry that can''t be quantified. I spend my days building models and finding patterns in data, but I know that the best things in life can''t be reduced to numbers. I''m analytical by nature but romantic by choice. Looking for someone who appreciates logic but also believes in magic, whatever that means to them.',
        'Consultant traveling every week but worth the wait. I work for a big firm and I''m on a plane more often than I''m home. But I''ve got status on every airline and points at every hotel, so our vacation game will be strong. I''m looking for someone independent who has their own life but wants to merge itineraries eventually. Long-distance dating? I''ve got it down to a science.',
        'Product manager who can definitely prioritize you in my backlog. I work in tech and I spend my days deciding what gets built and when. I''m organized, strategic, and I always have a plan. But I also know that the best things in life are the ones you don''t plan for. Looking for someone who can roll with ambiguity and doesn''t need every date scheduled three weeks in advance.',
        'Creative director seeking creative connections. I run a small agency and I spend my days dreaming up campaigns and bringing ideas to life. I''m surrounded by creative people all day, and I want that energy in my personal life too. Looking for someone who makes things - art, music, food, whatever - and isn''t afraid to share their creative process with me.'
    ];

    prompt_questions TEXT[] := ARRAY[
        'The way to win me over is',
        'My simple pleasures',
        'I get way too excited about',
        'We''ll get along if',
        'My love language is',
        'I''m looking for someone who',
        'Don''t hate me if I',
        'The key to my heart is',
        'A random fact I love is',
        'I''m weirdly attracted to'
    ];

    prompt_answers TEXT[] := ARRAY[
        'good food and even better conversation - I want to hear your hot takes and your unpopular opinions. Tell me about the book that changed your life or the trip that didn''t go as planned.',
        'coffee in bed on a lazy Sunday, long walks through the city when the weather is perfect, a really good playlist, and that moment when you finish a book and just sit there thinking about it.',
        'trying new restaurants and giving them very detailed reviews to my friends. I have a whole rating system. Yes, I''m that person. No, I don''t feel bad about it.',
        'you can handle my chaotic energy on weekends but also respect my need for quiet recharge time. I''m an extroverted introvert, if that makes any sense.',
        'quality time and acts of service. I show love by remembering the little things you mentioned and then surprising you with them later. I want someone who notices the effort.',
        'doesn''t take themselves too seriously but takes the things that matter very seriously. Someone who can laugh at themselves but also show up when it counts.',
        'sing loudly in the car even when I don''t know the words. Also, if I send you voice memos. Also, if I get really into true crime podcasts and have theories about everything.',
        'making me laugh until my cheeks hurt and I can''t breathe. Bonus points if it''s at an inappropriate time, like in a quiet museum or during a serious movie scene.',
        'octopuses have three hearts and blue blood. Also, honey never spoils - they''ve found 3000-year-old honey in Egyptian tombs that''s still perfectly edible. I collect random facts like this.',
        'people who get really passionate about random things. Tell me about your niche hobby, your controversial food opinion, your weird collection. I want to see what lights you up.'
    ];

    i INT;
    bio_idx INT;
    p1_idx INT;
    p2_idx INT;
    p3_idx INT;
    user_rec RECORD;
BEGIN
    i := 1;
    FOR user_rec IN SELECT user_id FROM profiles ORDER BY user_id LOOP
        bio_idx := 1 + ((i - 1) % array_length(long_bios, 1));
        p1_idx := 1 + ((i - 1) % array_length(prompt_questions, 1));
        p2_idx := 1 + (i % array_length(prompt_questions, 1));
        p3_idx := 1 + ((i + 1) % array_length(prompt_questions, 1));

        UPDATE profiles
        SET
            bio = long_bios[bio_idx],
            prompts = jsonb_build_array(
                jsonb_build_object('id', 'prompt_' || i || '_1', 'question', prompt_questions[p1_idx], 'answer', prompt_answers[1 + ((i - 1) % array_length(prompt_answers, 1))]),
                jsonb_build_object('id', 'prompt_' || i || '_2', 'question', prompt_questions[p2_idx], 'answer', prompt_answers[1 + (i % array_length(prompt_answers, 1))]),
                jsonb_build_object('id', 'prompt_' || i || '_3', 'question', prompt_questions[p3_idx], 'answer', prompt_answers[1 + ((i + 1) % array_length(prompt_answers, 1))])
            )
        WHERE user_id = user_rec.user_id;

        i := i + 1;
    END LOOP;
END $$;
